project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
 
  page-footer:
      right: "&copy; 2024, Sai Priyanka Iragavarapu"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto



